name: Publish
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          scope: '@tikpay'
          cache: 'npm'

      - run: npm i -g npm@latest

      - run: npm ci
      - run: npm run build

      - name: Test (unit)
        run: npm run test:unit
      - name: Test (integration)
        run: npm run test:int

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
