name: Publish
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    environment: release
    if: contains(github.event.head_commit.message, 'version packages')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          scope: '@tikpay'
          cache: 'npm'

      - run: npm i -g npm@latest

      - run: npm ci
      - run: npm run build

      - name: Test (unit)
        run: npm run test:unit
      - name: Test (integration)
        run: npm run test:int

      - name: Publish to npm (via Changesets)
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
